kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ml-platform
nodes:
  # Control plane node
  - role: control-plane
    extraPortMappings:
    # For ML model serving APIs
    - containerPort: 30000
      hostPort: 30000
      protocol: TCP
    # For Grafana dashboard
    - containerPort: 30001
      hostPort: 30001
      protocol: TCP
    # For Prometheus
    - containerPort: 30002
      hostPort: 30002
      protocol: TCP
  
  # Worker nodes for ML workloads
  - role: worker
    labels:
      workload: ml-training
    extraMounts:
    # Mount for model storage (simulates persistent volumes)
    - hostPath: ./models
      containerPath: /models
  
  - role: worker
    labels:
      workload: ml-inference
  
  - role: worker
    labels:
      workload: ml-inference
